apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <html>
      <head>
        <title>Welcome to Nginx! from actions</title>
      </head>
      <body>
        <h1>Welcome to Nginx!</h1>
        <p>This is a simple HTML page served by Nginx.through actions</p>
      </body>
    </html>