name: lab1-echo-output-check
on:
  workflow_dispatch:

jobs:
  echoOutput:
    runs-on: ubuntu-latest
    steps:
      - name: Echo output
        run: |
          echo "Hello, World!123123"
          ls -alh

