on:
    workflow_call:
        inputs:
            greeting:
                description: 'Greeting message'
                required: true
                default: 'Hello'
                type: string
            choose-color:
                description: 'Choose a color'
                required: true
                default: 'Red'
                type: string
        outputs:
            greet:
                description: 'Greeting output'
                value: ${{ jobs.print-color.outputs.greet }}
jobs:
    print-color:
        outputs:
            greet: ${{ steps.print-color.outputs.greet }}
        runs-on: ubuntu-latest
        steps:
            - name: Print the chosen color
              id: print-color
              run: |
                echo "You chose the color: ${{ inputs.choose-color }}"
                echo "greet=${{ inputs.greeting }} ${{inputs.choose-color}}" >> $GITHUB_OUTPUT
                echo " ${{greet}}"