name: resuable-workflow-lab6
on:
    workflow_dispatch:
jobs:
    call-reusable-workflow:
        uses: ./.github/workflows/lab6_reusable_workflow.yaml
        with:
            greeting: "Hello from the reusable workflow!"
            choose-color: "Green"