name: resuable-workflow-lab6
on:
    workflow_dispatch:
jobs:
    call-reusable-workflow:
        uses: ./.github/workflows/lab6_reusable_workflow.yaml
        with:
            greeting: "Hello"
            choose-color: 'Blue'
    use-reusable-workflow-output:
        needs: call-reusable-workflow
        runs-on: ubuntu-latest
        steps:
            - name: Use the output from reusable workflow
              run: |
                echo "Output from reusable workflow: ${{ needs.call-reusable-workflow.outputs.greet }}"