on:
    workflow_call:
        inputs:
            greeting:
                description: 'Greeting message'
                required: true
                default: 'Hello'
                type: string
            choose-color:
                description: 'Choose a color'
                required: true
                type: string
jobs:
    print-color:
        runs-on: ubuntu-latest
        steps:
            - name: Print the chosen color
              run: |
                echo "You chose the color: ${{ inputs.choose-color }}"
