name: lab to learn upload and download artifacts between jobs
on:
  workflow_dispatch:
jobs:
  upload-artifact:
    runs-on: vm-host
    steps:
      - name: Create a file to upload as artifact
        run: echo "This is a sample artifact file." > artifact.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: sample-artifact
          path: artifact.txt

  download-artifact:
    runs-on: vm-host
    needs: upload-artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: sample-artifact
          path: ./artifact-download
      - name: list-directory
        run: ls ./artifact-download
      - name: Display downloaded artifact content
        run: cat ./artifact-download/artifact.txt   
