on: [workflow_dispatch,push,pull_request]

jobs:
  composite-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run a composite action
        uses: ./.github/actions/lab9-composite
        with:
          who-to-greet: "Shaktiman"
      - name: Display the random number output from composite action
        run: echo "The random number is ${{ steps.composite-action.outputs.random-number }}"
        shell: bash