name: build and deploy an app to AKS
on:
  workflow_dispatch:

env:
    RESOURCE_GROUP: "3004-learning"
    CLUSTER_NAME: "aks-github-actions"
    DEPLOYMENT_MANIFEST_PATH: "./deploy.yaml"
    CONFIG_FILE: "./configmap.yaml"
    service_file: "./service.yaml"
permissions:
  id-token: write
  contents: read

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Checks out the repository this file is in
        uses: actions/checkout@v4
    # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
      - name: Debug identity
        run: |
          az account show || true
          az account list --output table

    
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure PowerShell script
        uses: azure/powershell@v3
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzContext       
            # Builds and pushes an image up to your Azure Container Registry
      - name: kubelogin-connect
        run: |
          az aks get-credentials -g ${{ env.RESOURCE_GROUP }} -n ${{ env.CLUSTER_NAME }} --admin
      - name: Deploy to AKS
        run: |
          kubectl apply -f ${{ env.CONFIG_FILE }}
          kubectl apply -f ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          kubectl apply -f ${{ env.service_file }}

           

